[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polychaos"
version = "0.1.0"
description = "A library for Polynomial Chaos Expansion."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Lucas Brunel"}]
license = {text = "LGPL-3.0-or-later"}
classifiers = [
    """License :: OSI Approved :: GNU Lesser General Public License v3 or\
     later (LGPLv3+)""",
]

dependencies = [
    "numpy>=2.4.0",
    "scipy>=1.17.0",
]

[project.optional-dependencies]
test = [
    "pytest>=9.0.0",
    "matplotlib>=3.10.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
